# SQL Server \u8A2D\u5B9A
spring.datasource.url=jdbc:sqlserver://localhost:1433;database=MRT;encrypt=true;trustServerCertificate=true
spring.datasource.username=sa
spring.datasource.password=P@ssw0rd
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

# JPA \u8A2D\u5B9A
spring.jpa.database-platform=org.hibernate.dialect.SQLServerDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.thymeleaf.cache=false

server.servlet.session.timeout=30m
server.servlet.session.cookie.http-only=true  

debug=true
logging.level.org.springframework=DEBUG

server.port=8098
server.address=0.0.0.0

# ? Gmail SMTP ??
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=fly155141@gmail.com
spring.mail.password=jpfb zotk zjpi hebu
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.default-encoding=UTF-8

spring.messages.basename=i18n/messages
spring.messages.encoding=UTF-8
